# file name: problemSetDay2.py
name= input("what is your name?")
print(name)
birthday=input("when is your birthday?")
print(birthday)
grade=input("what grade are you in?")
print(grade)
school=input("where do you go to school?")
print(school)
fav_subject=input("what is your favorite subject?")
print(fav_subject)
aspiration=input("what do you wanna be when you are older?")
print(aspiration)
b=input("what is the value of b?")
b=int(b)
a=input("what is the value of a?")
a=int(a)
c=input("what is the value of c?")
c=int(c)
